name: Maven Build
on:
  workflow_call:


jobs:
  build-maven:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - run: cd java
      - name: Build with Maven
        run: mvn -B package --file pom.xml
